spring:
  application:
    name: bank-info-service
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:


security:
  oauth2:
    resource:
      id: bank-info-service
      token-info-uri: http://localhost:8001/oauth/check_token
    client:
      client-id: bank-info-service
      client-secret: secret
      access-token-uri: http://localhost:8001/oauth/token
      user-authorization-uri: http://localhost:8001/oauth/authorize

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

account-service:
  account-url: http://account-service/account


management:
  endpoints:
    web:
      exposure:
        include: "*"
