security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8001/oauth/check_token
    client:
      client-id: monitoring
      client-secret: secret
      access-token-uri: http://localhost:8001/oauth/token
      user-authorization-uri: http://localhost:8001/oauth/authorize

spring:
  application:
    name: monitoring
  boot:
    admin:
      url: http://localhost:8080
    application:
      name: monitoring

management:
  endpoints:
    web:
      exposure:
        include: "*"